# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: # TODO your secret here
  google: # TODO create a key on GoogleAPIs console for server
    global_key: # TODO gen a Global
    web: # TODO create it web
      secret_key:
      client_id:
    server: # TODO create it service click in GENERATE JSON
      private_key_id:
      private_key:
      client_email:
      client_id:
      type: service_account
  facebook: # TODO create a Facebook App and add it here
    app_id: # TODO ID from the App
    app_secret: # TODO Secret from the app
    app_permissions: email, publish_stream, manage_pages, read_stream # TODO checkout what permissions your app use
    redir_url: http://localhost:4000/socials/auth/facebook

test:
  secret_key_base: # TODO your secret here
  google: # TODO create a key on GoogleAPIs console for server
    global_key: # TODO gen a Global
    web: # TODO create it web
      secret_key:
      client_id:
    server: # TODO create it service click in GENERATE JSON
      private_key_id:
      private_key:
      client_email:
      client_id:
      type: service_account
  facebook: # TODO create a Facebook App and add it here
    app_id: # TODO ID from the App
    app_secret: # TODO Secret from the app
    app_permissions: email, publish_stream, manage_pages, read_stream # TODO checkout what permissions your app use
    redir_url: http://localhost:4000/socials/auth/facebook

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  rents:
    app_id: # TODO copy it from RentS page
    app_secret_key: # TODO copy it from RentS page
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
