# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: # TODO your secret here
  rents:
    app_id: 4
    app_secret_key: $2a$10$e3DOeo82OhIkKqVUDJ9eEeHuBZuPpD8QT9GOK7C0p2K5zkxRplus.

test:
  secret_key_base: # TODO your secret here
  rents:
      app_id: 4
      app_secret_key: $2a$10$e3DOeo82OhIkKqVUDJ9eEeHuBZuPpD8QT9GOK7C0p2K5zkxRplus.

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  rents:
    app_id: # TODO copy it from RentS page
    app_secret_key: # TODO copy it from RentS page
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
