# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: # TODO your secret here
  cielo_page:
    numero_afiliacao: 1001734898
    chave_acesso: e84827130b9837473681c2787007da5914d6359947015a5cdb2b8843db0fa832
  cielo_loja:
    numero_afiliacao: 1006993069
    chave_acesso: 25fbb99741c739dd84d7b06ec78c9bac718838630f30b112d033ce2e621b34f3
  facebook: # TODO create a Facebook App and add it here
    app_id: # TODO ID from the App
    app_secret: # TODO Secret from the app
    app_permissions: email, publish_stream, manage_pages, read_stream # TODO checkout what permissions your app use
    redir_url: http://localhost:4000/socials/auth/facebook

test:
  secret_key_base: # TODO your secret here
  cielo_page:
    numero_afiliacao: 1001734898
    chave_acesso: e84827130b9837473681c2787007da5914d6359947015a5cdb2b8843db0fa832
  cielo_loja:
    numero_afiliacao: 1006993069
    chave_acesso: 25fbb99741c739dd84d7b06ec78c9bac718838630f30b112d033ce2e621b34f3
  facebook: # TODO create a Facebook App and add it here
    app_id: # TODO ID from the App
    app_secret: # TODO Secret from the app
    app_permissions: email, publish_stream, manage_pages, read_stream # TODO checkout what permissions your app use
    redir_url: http://localhost:4000/socials/auth/facebook

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
